model_info:
  model_name: deepseek-v3-250324
  model2_name: doubao-1-5-pro-32k-250115
  base_url:
  api_key:
  temperature:
vkdb:
  ak:
  sk:
  region: cn-beijing
  host: api-vikingdb.volces.com
  scheme: https
